### ISSUE TITLE
How to manage .env files

### ISSUE THREAD

**Issue by razzeee** [redwoodjs/docker#53]
I'm triyng to use the example from https://github.com/redwoodjs/docker/blob/main/docker/jeliasson-nginx/web/Dockerfile to deploy to docker and it seems to work fine.

But as soon as I try to access something, that needs to access one of my env variables, it crashes, because the env var is empty.

I patched around a bunch of things, and I can see in docker, that I have the expected env vars via `printenv`, but I guess redwood needs them in a `.env` file somewhere at some point?

**Comment by razzeee** [comment]
Seems the missing bit was this for me:

Pass your env variables via args to the dockerfile build. Then map those to env variables again, like it's already done in the example files.
```
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        - GITLAB_CLIENT_ID=${GITLAB_CLIENT_ID}
        - GITLAB_REDIRECT_URI=${GITLAB_REDIRECT_URI}
        - GITLAB_AUTHORITY=${GITLAB_AUTHORITY}

```

```
ARG GITLAB_CLIENT_ID
ENV GITLAB_CLIENT_ID=$GITLAB_CLIENT_ID
ARG GITLAB_REDIRECT_URI
ENV GITLAB_REDIRECT_URI=$GITLAB_REDIRECT_URI
ARG GITLAB_AUTHORITY
ENV GITLAB_AUTHORITY=$GITLAB_AUTHORITY

```
